// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.app2.app2t.domain.em;

import com.app2.app2t.domain.em.EMPosition;
import com.app2.app2t.domain.em.EMPositionDataOnDemand;
import com.app2.app2t.domain.em.EMPositionIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect EMPositionIntegrationTest_Roo_IntegrationTest {
    
    declare @type: EMPositionIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: EMPositionIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: EMPositionIntegrationTest: @Transactional;
    
    @Autowired
    EMPositionDataOnDemand EMPositionIntegrationTest.dod;
    
    @Test
    public void EMPositionIntegrationTest.testCountEMPositions() {
        Assert.assertNotNull("Data on demand for 'EMPosition' failed to initialize correctly", dod.getRandomEMPosition());
        long count = EMPosition.countEMPositions();
        Assert.assertTrue("Counter for 'EMPosition' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void EMPositionIntegrationTest.testFindEMPosition() {
        EMPosition obj = dod.getRandomEMPosition();
        Assert.assertNotNull("Data on demand for 'EMPosition' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'EMPosition' failed to provide an identifier", id);
        obj = EMPosition.findEMPosition(id);
        Assert.assertNotNull("Find method for 'EMPosition' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'EMPosition' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void EMPositionIntegrationTest.testFindAllEMPositions() {
        Assert.assertNotNull("Data on demand for 'EMPosition' failed to initialize correctly", dod.getRandomEMPosition());
        long count = EMPosition.countEMPositions();
        Assert.assertTrue("Too expensive to perform a find all test for 'EMPosition', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<EMPosition> result = EMPosition.findAllEMPositions();
        Assert.assertNotNull("Find all method for 'EMPosition' illegally returned null", result);
        Assert.assertTrue("Find all method for 'EMPosition' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void EMPositionIntegrationTest.testFindEMPositionEntries() {
        Assert.assertNotNull("Data on demand for 'EMPosition' failed to initialize correctly", dod.getRandomEMPosition());
        long count = EMPosition.countEMPositions();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<EMPosition> result = EMPosition.findEMPositionEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'EMPosition' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'EMPosition' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void EMPositionIntegrationTest.testFlush() {
        EMPosition obj = dod.getRandomEMPosition();
        Assert.assertNotNull("Data on demand for 'EMPosition' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'EMPosition' failed to provide an identifier", id);
        obj = EMPosition.findEMPosition(id);
        Assert.assertNotNull("Find method for 'EMPosition' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyEMPosition(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'EMPosition' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void EMPositionIntegrationTest.testMergeUpdate() {
        EMPosition obj = dod.getRandomEMPosition();
        Assert.assertNotNull("Data on demand for 'EMPosition' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'EMPosition' failed to provide an identifier", id);
        obj = EMPosition.findEMPosition(id);
        boolean modified =  dod.modifyEMPosition(obj);
        Integer currentVersion = obj.getVersion();
        EMPosition merged = (EMPosition)obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'EMPosition' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void EMPositionIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'EMPosition' failed to initialize correctly", dod.getRandomEMPosition());
        EMPosition obj = dod.getNewTransientEMPosition(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'EMPosition' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'EMPosition' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'EMPosition' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void EMPositionIntegrationTest.testRemove() {
        EMPosition obj = dod.getRandomEMPosition();
        Assert.assertNotNull("Data on demand for 'EMPosition' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'EMPosition' failed to provide an identifier", id);
        obj = EMPosition.findEMPosition(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'EMPosition' with identifier '" + id + "'", EMPosition.findEMPosition(id));
    }
    
}
