// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.app2.app2t.domain.em;

import com.app2.app2t.domain.em.EMTeam;
import com.app2.app2t.domain.em.EMTeamDataOnDemand;
import com.app2.app2t.domain.em.EMTeamIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect EMTeamIntegrationTest_Roo_IntegrationTest {
    
    declare @type: EMTeamIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: EMTeamIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: EMTeamIntegrationTest: @Transactional;
    
    @Autowired
    EMTeamDataOnDemand EMTeamIntegrationTest.dod;
    
    @Test
    public void EMTeamIntegrationTest.testCountEMTeams() {
        Assert.assertNotNull("Data on demand for 'EMTeam' failed to initialize correctly", dod.getRandomEMTeam());
        long count = EMTeam.countEMTeams();
        Assert.assertTrue("Counter for 'EMTeam' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void EMTeamIntegrationTest.testFindEMTeam() {
        EMTeam obj = dod.getRandomEMTeam();
        Assert.assertNotNull("Data on demand for 'EMTeam' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'EMTeam' failed to provide an identifier", id);
        obj = EMTeam.findEMTeam(id);
        Assert.assertNotNull("Find method for 'EMTeam' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'EMTeam' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void EMTeamIntegrationTest.testFindAllEMTeams() {
        Assert.assertNotNull("Data on demand for 'EMTeam' failed to initialize correctly", dod.getRandomEMTeam());
        long count = EMTeam.countEMTeams();
        Assert.assertTrue("Too expensive to perform a find all test for 'EMTeam', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<EMTeam> result = EMTeam.findAllEMTeams();
        Assert.assertNotNull("Find all method for 'EMTeam' illegally returned null", result);
        Assert.assertTrue("Find all method for 'EMTeam' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void EMTeamIntegrationTest.testFindEMTeamEntries() {
        Assert.assertNotNull("Data on demand for 'EMTeam' failed to initialize correctly", dod.getRandomEMTeam());
        long count = EMTeam.countEMTeams();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<EMTeam> result = EMTeam.findEMTeamEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'EMTeam' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'EMTeam' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void EMTeamIntegrationTest.testFlush() {
        EMTeam obj = dod.getRandomEMTeam();
        Assert.assertNotNull("Data on demand for 'EMTeam' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'EMTeam' failed to provide an identifier", id);
        obj = EMTeam.findEMTeam(id);
        Assert.assertNotNull("Find method for 'EMTeam' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyEMTeam(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'EMTeam' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void EMTeamIntegrationTest.testMergeUpdate() {
        EMTeam obj = dod.getRandomEMTeam();
        Assert.assertNotNull("Data on demand for 'EMTeam' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'EMTeam' failed to provide an identifier", id);
        obj = EMTeam.findEMTeam(id);
        boolean modified =  dod.modifyEMTeam(obj);
        Integer currentVersion = obj.getVersion();
        EMTeam merged = (EMTeam)obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'EMTeam' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void EMTeamIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'EMTeam' failed to initialize correctly", dod.getRandomEMTeam());
        EMTeam obj = dod.getNewTransientEMTeam(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'EMTeam' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'EMTeam' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'EMTeam' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void EMTeamIntegrationTest.testRemove() {
        EMTeam obj = dod.getRandomEMTeam();
        Assert.assertNotNull("Data on demand for 'EMTeam' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'EMTeam' failed to provide an identifier", id);
        obj = EMTeam.findEMTeam(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'EMTeam' with identifier '" + id + "'", EMTeam.findEMTeam(id));
    }
    
}
